[package]
authors = ["CaffeeLake <PascalCoffeeLake@gmail.com>"]
description = ""
edition = "2024"
name = "kyoshin-sensor-tui"
version = "0.1.0"

[lib]
name = "kyoshin_sensor_tui"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1.13", features = [
  "attributes",
  "tokio1",
  "unstable",
] }
chrono = "0.4"
clap = { version = "4.6", features = ["derive", "env"] }
crossterm = "0.29"
encoding_rs = "0.8"
futures = "0.3"
ism330dhcx = "0.6"
linux-embedded-hal = "0.5"
rayon = "1.12"
rustfft = "6.4"
